services:
  php:
      build:
          context: .
          dockerfile: docker/php/Dockerfile
          target: ${DOCKER_TARGET:-prod}
      image: boat-trips:latest
      container_name: boat-trips-php
      ports:
          - "${HOST_PORT:-80}:8080"
      environment:
          APP_ENV: ${APP_ENV:-prod}
          APP_SECRET: ${APP_SECRET}
      restart: always
